services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: wirechat-app:latest
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      RUN_MIGRATIONS: "true"
    volumes:
      - storage_data:/var/www/html/storage

volumes:
  storage_data:
